version: '3.8'

services:
  db:
    container_name: tyr-db
    build:
      context: .
      args:
        POSTGIS_VERSION: ${POSTGIS_VERSION}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      RUN_INIT: ${RUN_INIT}
    ports:
      - "${HOST_DB_PORT}:${DEFAULT_POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ${GADM_FILE}:/data/gadm/gadm.gpkg

  backend:
    container_name: tyr-backend
    build: ${BACKEND_PATH}
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
    depends_on:
      - db
    volumes:
      - gadm_data:/data/gadm
    ports:
      - "${HOST_BACKEND_PORT}:${DEFAULT_NODEJS_PORT}"

  frontend:
    container_name: tyr-frontend
    build: ${FRONTEND_PATH}
    environment:
      REACT_APP_API_URL: http://${BACKEND_HOST}:${HOST_BACKEND_PORT}
    depends_on:
      - backend
    ports:
      - "${HOST_FRONTEND_PORT}:${DEFAULT_REACT_PORT}"

volumes:
  postgres_data:
    driver: local
  gadm_data:
    driver: local
