version: '3.8'

services:
  tyr-db:
    build:
      context: .
      args:
        GADM_FILE: ${GADM_FILE}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${HOST_DB_PORT}:${DEFAULT_POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - gadm_data:/data/gadm

  backend:
    build: ${BACKEND_PATH}
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: tyr-db
    depends_on:
      - tyr-db
    volumes:
      - gadm_data:/data/gadm
    ports:
      - "${HOST_BACKEND_PORT}:${DEFAULT_NODEJS_PORT}"

  frontend:
    build: ${FRONTEND_PATH}
    environment:
      REACT_APP_API_URL: http://${BACKEND_HOST}:${HOST_BACKEND_PORT}
    depends_on:
      - backend
    ports:
      - "${HOST_FRONTEND_PORT}:${DEFAULT_REACT_PORT}"

volumes:
  postgres_data:
    driver: local
  gadm_data:
    driver: local
