name: Directory Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-dirs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2  # Fetch the last two commits

    - name: Check directories
      run: ./.shared-scripts/check_directories.sh github-action

