name: ESLint Backend Check

on:
  pull_request:
    branches: [ main ]
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  check-paths:
    runs-on: ubuntu-latest
    outputs:
      run-lint: ${{ steps.paths-filter.outputs.backend }}
    steps:
      - uses: actions/checkout@v4
      - id: paths-filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            backend:
              - 'backend/**/*.js'
              - 'backend/**/*.md'

  lint-backend:
    needs: check-paths
    if: needs.check-paths.outputs.run-lint == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ./backend/node_modules
          key: ${{ runner.os }}-back-node-${{ hashFiles('./backend/package.json') }}

      - name: Install dependencies
        run: npm install
        working-directory: ./backend

      - name: Run ESLint
        run: npm run lint
        working-directory: ./backend
